import { NextRequest, NextResponse } from "next/server";
import { generateCreativeBrief } from "../../../../../../lib/creative/agent";
import { buildHiggsfieldMcpTasks } from "../../../../../../lib/creative/higgsfield-mcp";
import {
  createOrUpdateCreativeVideoJob,
  getCampaign,
  getCreativeVideoJob,
  getCreativeVideoScenes,
  getLead,
  queueCreativeVideoScenes,
  replaceCreativeVideoScenes,
  saveLeadResearch,
  saveLeadScript,
} from "../../../../../../lib/integrations/supabase";

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ leadId: string }> }
) {
  try {
    const { leadId } = await params;
    const body = await request.json().catch(() => ({}));
    const forceRegenerate = Boolean(
      (body as { forceRegenerate?: unknown; force?: unknown }).forceRegenerate ??
        (body as { force?: unknown }).force
    );
    const lead = await getLead(leadId);
    if (!lead) {
      return NextResponse.json({ error: "Lead not found" }, { status: 404 });
    }
    if (!lead.profilePhotoUrl) {
      return NextResponse.json(
        { error: "Upload the lead LinkedIn profile photo before starting automation" },
        { status: 400 }
      );
    }

    const campaign = await getCampaign(lead.campaignId);
    if (!campaign) {
      return NextResponse.json({ error: "Campaign not found" }, { status: 404 });
    }

    let job = await getCreativeVideoJob(leadId);
    let scenes = await getCreativeVideoScenes(leadId);
    const hasQueuedScenes = scenes.some((scene) => scene.status === "queued");
    const hasGeneratingScenes = scenes.some((scene) => scene.status === "generating");
    const hasReadyScenes = scenes.some((scene) => scene.status === "ready");
    const hasProtectedScenes = hasQueuedScenes || hasGeneratingScenes || hasReadyScenes;

    if (hasProtectedScenes) {
      return NextResponse.json({
        job,
        scenes,
        mcpTasks: buildHiggsfieldMcpTasks(lead, job!, scenes, campaign),
        automationMessage: hasGeneratingScenes
          ? "This lead is already being generated by Higgsfield, so ReachAI did not start another run or spend extra credits."
          : hasQueuedScenes
            ? "This lead is already waiting for the Higgsfield worker, so ReachAI did not queue it again or spend extra credits."
            : "This lead already has generated scene videos, so ReachAI did not start another run or spend extra credits.",
        automationMode: "already_queued_or_ready",
      });
    }

    if (forceRegenerate || !job || scenes.length === 0) {
      const { clientResearchSummary, leadResearchSummary, creativeBrief } =
        await generateCreativeBrief(campaign, lead);

      await saveLeadResearch(leadId, leadResearchSummary);
      await saveLeadScript(
        leadId,
        creativeBrief.voiceoverScript,
        creativeBrief.outreachMessage
      );

      job = await createOrUpdateCreativeVideoJob({
        leadId,
        campaignId: campaign.id,
        status: "prompt_ready",
        clientResearchSummary,
        leadResearchSummary,
        salesAngle: creativeBrief.salesAngle,
        voiceoverScript: creativeBrief.voiceoverScript,
        outreachMessage: creativeBrief.outreachMessage,
        creativeBrief,
      });

      scenes = await replaceCreativeVideoScenes(job.id, leadId, creativeBrief.scenePlan);
    }

    await queueCreativeVideoScenes(leadId);
    scenes = await getCreativeVideoScenes(leadId);

    job = await createOrUpdateCreativeVideoJob({
      leadId,
      campaignId: campaign.id,
      status: "scenes_queued",
    });

    return NextResponse.json({
      job,
      scenes,
      mcpTasks: buildHiggsfieldMcpTasks(lead, job, scenes, campaign),
      automationMessage:
        "The brief is ready and the 3 UGC hook scene jobs are lined up. As soon as the connected Higgsfield generator starts, this page will switch to creating the videos automatically.",
      automationMode: "mcp_worker_required",
    });
  } catch (error) {
    console.error("Error starting creative automation:", error);
    return NextResponse.json(
      {
        error:
          error instanceof Error
            ? error.message
            : "Failed to start creative automation",
      },
      { status: 500 }
    );
  }
}
